spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/trendpulse
  
  data:
    redis:
      host: redis

app:
  minio:
    endpoint: http://minio:9000

logging:
  level:
    root: INFO
    com.trendpulse: INFO
